### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by umeshn** [cappelletto/bayesian-inference#37]
While running pip install -U .
or  pip install -U -e .

Processing /home/umesh/datadrive/Software/Gitclones/Autoencoder/bnn_inference
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/umesh/datadrive/Software/Gitclones/Autoencoder/bnn_inference/setup.py", line 18, in <module>
          exec(ver_file.read(), main_ns)
        File "<string>", line 18, in <module>
        File "/home/umesh/anaconda3/envs/blitz/lib/python3.9/site-packages/git/refs/symbolic.py", line 219, in _get_object
          return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
        File "/home/umesh/anaconda3/envs/blitz/lib/python3.9/site-packages/git/objects/base.py", line 94, in new_from_sha
          oinfo = repo.odb.info(sha1)
        File "/home/umesh/anaconda3/envs/blitz/lib/python3.9/site-packages/git/db.py", line 40, in info
          hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
        File "/home/umesh/anaconda3/envs/blitz/lib/python3.9/site-packages/git/cmd.py", line 1383, in get_object_header
          return self.__get_object_header(cmd, ref)
        File "/home/umesh/anaconda3/envs/blitz/lib/python3.9/site-packages/git/cmd.py", line 1370, in __get_object_header
          return self._parse_object_header(cmd.stdout.readline())
        File "/home/umesh/anaconda3/envs/blitz/lib/python3.9/site-packages/git/cmd.py", line 1329, in _parse_object_header
          raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
      ValueError: SHA could not be resolved, git returned: b''
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cappelletto** [comment]
@umeshn coudl you please run 
``` conda list ``` 
with the env *blitz* activated?

**Comment by cappelletto** [comment]
Possibly related to broken/missing local git database information.
**version.py** is the offending module

**Comment by cappelletto** [comment]
Should be fixed with latest PR [https://github.com/cappelletto/bayesian-inference/pull/40]
